
---
STATIC_ADDRESS_VAR: ""
MYSQL_HOST_VAR: ""
MYSQL_USER_VAR: ""
MYSQL_PASSWORD_VAR: ""
MYSQL_SCHEMA_VAR: ""
SIP_BALANCER_VAR: ""
VOICERSS_KEY_VAR: ""
UNIT_NAME_VAR: ""
RESTCOMM_PASSWORD_VAR: ""
SMS_OUTBOUND_PROXY_VAR: ""