
---
EXTERNAL_IP_VAR: ""
REDIS_SERVICE_HOST_VAR: ""
REDIS_SERVICE_PORT_VAR:
RESTCOMM_SERVICE_VAR: ""
UNIT_NAME_VAR: ""
RESTCOMM_USER_VAR: ""
RESTCOMM_PASSWORD_VAR: ""
PHONE_NUMBER_VAR: ""
DID_DOMAIN_VAR: ""
