
---
UNIT_NAME_VAR: "{{ UNIT_NAME_VAR | default("") }}"
REDIS_SERVICE_HOST_VAR: "{{ REDIS_SERVICE_HOST_VAR | default("") }}"
REDIS_SERVICE_PORT_VAR: {{ REDIS_SERVICE_PORT_VAR | default(0) }}
OPENCELL_SERVICE_VAR: "{{ OPENCELL_SERVICE_VAR | default("") }}"
OPENCELL_USER_VAR: "{{ OPENCELL_USER_VAR | default("") }}"
OPENCELL_PASSWORD_VAR: "{{ OPENCELL_PASSWORD_VAR | default("") }}"
RESTCOMM_SERVICE_VAR: "{{ RESTCOMM_SERVICE_VAR | default("") }}"
RESTCOMM_USER_VAR: "{{ RESTCOMM_USER_VAR | default("") }}"
RESTCOMM_PASSWORD_VAR: "{{ RESTCOMM_PASSWORD_VAR | default("") }}"
HOSTNAME_VAR: "{{ HOSTNAME_VAR | default("") }}"
