
---
UNIT_NAME_VAR: ""
REDIS_SERVICE_HOST_VAR: ""
REDIS_SERVICE_PORT_VAR:
OPENCELL_SERVICE_VAR: ""
OPENCELL_USER_VAR: ""
OPENCELL_PASSWORD_VAR: ""
RESTCOMM_SERVICE_VAR: ""
RESTCOMM_USER_VAR: ""
RESTCOMM_PASSWORD_VAR: ""
HOSTNAME_VAR: ""